import React, { memo, useMemo, useState, useEffect } from 'react';
import cx from 'clsx';
import useI18n from '@hooks/useI18n';
import Decimal from 'decimal.js';
import { numberWithCommas, trimDecimalZeros } from '@utils/numberUtils';
import { ReactComponent as InfoIcon } from '@assets/icons/info.svg';
import { usePools } from '@service/earn';
import TokenPair from '@modules/Position/TokenPair';
import Spin from '@components/Spin';
import Dropdown from '@components/Dropdown';
import BorderBox from '@components/Box/BorderBox';
import { getTokensPrice } from '@service/pairs&pool';
import { getUnwrapperTokenByAddress, type Token } from '@service/tokens';
import FarmIcon from '@assets/imgs/farm.png';
import { useNavigate } from 'react-router-dom';
import { setTokens } from './AddLiquidity/SelectPair';
import { useFarmsOnly } from '@service/earn';
import { setCurrentFee } from './AddLiquidity/SelectFeeTier';

const classNames = {
  title: 'flex items-center color-gray-normal text-xs not-italic leading-24px mb-8px lt-mobile:mb-4px',
  content: 'color-black-normal text-14px font-normal not-italic leading-18px lt-mobile:text-12px lt-mobile:leading-15px',
  authConnectButton:
    'flex items-center justify-center !px-6 h-8 border-2 border-solid rounded-full leading-18px font-normal whitespace-nowrap not-italic color-orange-normal cursor-pointer lt-mobile:border-1 lt-mobile:text-14px',
  splitLine: `lt-mobile:before:content-[''] lt-mobile:before:border-0 lt-mobile:before:border-l-1px lt-mobile:before:border-solid lt-mobile:before:absolute lt-mobile:before:top-2px lt-mobile:before:bottom-2px lt-mobile:relative lt-mobile:before:left-0 lt-mobile:before:border-color-orange-light`,
  poolWrapper: 'lt-mobile:mb-4 lt-mobile:rounded-14px',
  symbol: 'lt-mobile:font-normal lt-mobile:text-14px lt-mobile:leading-18px',
  fee: 'lt-mobile:h-18px lt-mobile:text-12px lt-mobile:leading-18px',
};

const transitions = {
  en: {
    poolName: 'Pool Name',
    APR: 'APR',
    range: 'Range',
    tvl: 'TVL',
    volume: 'Volume 24H',
    addLiquidity: 'Add Liquidity',
  },
  zh: {
    poolName: 'Pool Name',
    APR: 'APR',
    range: 'Range',
    tvl: 'TVL',
    volume: 'Volume 24H',
    addLiquidity: 'Add Liquidity',
  },
} as const;

interface APRData {
  rewardTokenAPRs: {
    [tokenAddress: string]: {
      apr: string;
      token: Token;
    };
  };
  feeApr: string;
  totalApr: string;
  hasValidData: boolean;
}

const APRDetail: React.FC<{ aprData: APRData; isSupportFarm: boolean }> = memo(({ aprData, isSupportFarm }) => {
  return (
    <BorderBox variant="gradient-white" className="max-w-90vw w-370px p-16px rounded-28px">
      {isSupportFarm ? (
        <p className="text-12px text-black-normal font-medium leading-20px">Estimated according to trading activity in the past 24 hours plus LP fees and farming rewards.</p>
      ) : (
        <p className="text-12px text-black-normal font-medium leading-20px">APR is calculated based on the fees generated by the pool over the last 24 hours.</p>
      )}
      <div className="mt-10px flex items-center justify-between text-14px text-black-normal">
        <span>Fees</span>
        <span>{aprData.feeApr}%</span>
      </div>
      {Object.entries(aprData?.rewardTokenAPRs ?? {}).map(([tokenAddress, { apr, token }]) => (
        <div className="mt-10px flex items-center justify-between text-14px text-black-normal" key={tokenAddress}>
          <span>{token.symbol} Rewards</span>
          <span>{apr}%</span>
        </div>
      ))}

      <BorderBox variant="gradient-white" className="h-0 border-1px border-b-0 bg-black-normal/10 mt-18px mb-12px" />

      <div className="flex items-center justify-between text-18px leading-22px text-black-normal font-medium">
        <span>Total APR</span>
        <span>{aprData?.totalApr}%</span>
      </div>
    </BorderBox>
  );
});

const PoolItem: React.FC<{ data: NonNullable<ReturnType<typeof usePools>>[number] }> = ({ data }) => {
  const navigate = useNavigate();
  const i18n = useI18n(transitions);

  const isSupportFarm = data.incentiveKeys.some((key) => key.status === 'active');

  const { tvl } = data;

  const tvlDisplay = useMemo(() => {
    if (tvl) {
      return `$${numberWithCommas(trimDecimalZeros(tvl.toFixed(2)))}`;
    }
    return '--';
  }, [tvl]);

  const rewardTokenAddresses = useMemo(() => {
    if (!data?.incentiveKeys) return [];
    const addresses = data.incentiveKeys.map((key) => key.rewardToken.toLowerCase());
    return [...new Set(addresses)];
  }, [data?.incentiveKeys]);

  const [rewardTokenPrices, setRewardTokenPrices] = useState<{ [key: string]: string | null } | null | undefined>(undefined);

  useEffect(() => {
    if (!rewardTokenAddresses.length) {
      setRewardTokenPrices(null);
      return;
    }

    getTokensPrice(rewardTokenAddresses)
      .then(setRewardTokenPrices)
      .catch((error) => {
        console.warn('Failed to fetch reward token prices:', error);
        setRewardTokenPrices(null);
      });
  }, [rewardTokenAddresses]);

  const volume24hDisplay = useMemo(() => {
    if (data.volume24h) {
      return `$${numberWithCommas(trimDecimalZeros(data.volume24h.toFixed(2)))}`;
    }
    return '--';
  }, [data.volume24h]);
  const feeAprDecimal = useMemo(() => {
    if (!tvl || tvl.equals(0) || !data.pairInfo.fee || !data.volume24h) return new Decimal(0);
    const feeDay = data.volume24h.mul(data.pairInfo.fee).div(1000000);
    return feeDay.mul(365).div(tvl).mul(100);
  }, [tvl, data.pairInfo.fee, data.volume24h]);

  const aprData: APRData = useMemo(() => {
    const _rewardTokenPrices = rewardTokenPrices ?? {};
    const _tvl = tvl ?? new Decimal(0);
    const incentiveKeys = data?.incentiveKeys ?? [];
    const incentives = data?.incentives ?? [];
    const rewards = data?.rewards ?? [];

    const rewardTokenAPRs: { [tokenAddress: string]: { apr: string; token: Token } } = {};
    const rewardTokenValues: { [tokenAddress: string]: { value: Decimal; token: Token } } = {};
    let totalRewardsPerSecond = new Decimal(0);

    incentiveKeys.forEach((key, index) => {
      const incentive = incentives[index];
      if (!incentive || key.status !== 'active' || incentive.isEmpty) return;

      const rewardTokenAddress = key.rewardToken.toLowerCase();

      const rewardTokenPrice = _rewardTokenPrices[rewardTokenAddress];
      if (!rewardTokenPrice) return;

      const rewardToken = rewards.find((r) => r.token?.address?.toLowerCase() === rewardTokenAddress)?.token;
      if (!rewardToken) return;

      const rewardValuePerSecond = new Decimal(incentive.rewardRate.toString()).div(new Decimal(10).pow(rewardToken.decimals)).mul(rewardTokenPrice);
      totalRewardsPerSecond = totalRewardsPerSecond.add(rewardValuePerSecond);

      if (rewardTokenValues[rewardTokenAddress]) {
        rewardTokenValues[rewardTokenAddress].value = rewardTokenValues[rewardTokenAddress].value.add(rewardValuePerSecond);
      } else {
        rewardTokenValues[rewardTokenAddress] = { value: rewardValuePerSecond, token: rewardToken };
      }
    });

    rewards.forEach(({ token: origin }) => {
      if (!origin) return;
      const tokenAddress = origin.address.toLowerCase();
      const token = getUnwrapperTokenByAddress(tokenAddress);
      if (!token) return;
      const value = rewardTokenValues[tokenAddress]?.value;
      if (!_rewardTokenPrices[tokenAddress] || !value)
        rewardTokenAPRs[tokenAddress] = {
          apr: '--',
          token,
        };
      else {
        const baseAPR = _tvl.isZero() ? new Decimal(0) : value.div(_tvl).mul(31536000);
        rewardTokenAPRs[tokenAddress] = {
          apr: baseAPR.toFixed(2),
          token,
        };
      }
    });

    const totalBaseAPR = _tvl.isZero() ? new Decimal(0) : totalRewardsPerSecond.div(_tvl).mul(31536000).add(feeAprDecimal);

    const totalApr = totalBaseAPR.toFixed(2);

    return {
      rewardTokenAPRs,
      feeApr: feeAprDecimal.toFixed(2),
      totalApr,
      hasValidData: !totalBaseAPR.isZero(),
    };
  }, [data?.incentiveKeys, data?.incentives, data?.rewards, tvl, rewardTokenPrices, feeAprDecimal]);

  return (
    <div
      className={`bg-orange-light-hover rounded-2xl mb-6 last:mb-0 py-4 px-8 relative grid grid-cols-17 lt-mobile:grid-cols-3 lt-mobile:px-2 lt-mobile:border-orange-light lt-mobile:border-solid lt-mobile:border-1px ${classNames.poolWrapper}`}
    >
      <div className="col-span-5 lt-mobile:col-span-3 lt-mobile:mb-16px">
        <div className={`${classNames.title}`}>
          <span>{i18n.poolName}</span>
          {isSupportFarm && <img src={FarmIcon} alt="farm" className="w-24px h-24px" />}
        </div>
        <div className={`${classNames.content} inline-flex justify-center items-center`}>
          <TokenPair
            position={
              {
                leftToken: data.pairInfo.leftToken,
                rightToken: data.pairInfo.rightToken,
                fee: data.pairInfo.fee,
              } as any
            }
            symbolClassName={classNames.symbol}
            feeClassName={classNames.fee}
          />
        </div>
      </div>
      <div className="col-span-3 lt-mobile:col-span-1">
        <div className={`${classNames.title}`}>
          {i18n.APR}
          <Dropdown Content={<APRDetail aprData={aprData} isSupportFarm={isSupportFarm} />} placement="top" trigger="mouseenter">
            <span className="w-12px h-full flex items-center ml-6px">
              <InfoIcon className="w-12px h-12px" />
            </span>
          </Dropdown>
        </div>
        <div className={`${classNames.content}`}>{rewardTokenPrices === undefined ? <Spin /> : aprData?.hasValidData ? `${aprData.totalApr}%` : '--'}</div>
      </div>
      <div className="col-span-3 lt-mobile:col-span-1">
        <div className={`lt-mobile:w-fit lt-mobile:mx-auto lt-mobile:pl-3 ${classNames.splitLine}`}>
          <div className={cx(classNames.title, 'lt-mobile:justify-center')}>{i18n.tvl}</div>
          <div className={cx(classNames.content, 'lt-mobile:text-center')}>{tvlDisplay}</div>
        </div>
      </div>
      <div className="col-span-3 lt-mobile:col-span-1">
        <div className={`lt-mobile:w-fit lt-mobile:ml-auto lt-mobile:pl-3 ${classNames.splitLine}`}>
          <div className={cx(classNames.title, 'lt-mobile:justify-end')}>{i18n.volume}</div>
          <div className={cx(classNames.content, 'flex items-center gap-2px lt-mobile:justify-end')}>{volume24hDisplay}</div>
        </div>
      </div>
      <div className="flex items-center justify-end col-span-3 lt-mobile:absolute lt-mobile:right-2 lt-mobile:top-[28px]">
        <div
          className={classNames.authConnectButton}
          id={`add-liquidity-button-${data.poolAddress}`}
          onClick={() => {
            if (!data.pairInfo.leftToken || !data.pairInfo.rightToken) return;
            setTokens(data.pairInfo.leftToken, data.pairInfo.rightToken);
            setCurrentFee(data.pairInfo.fee);
            navigate('/earn/add_liquidity');
          }}
        >
          {i18n.addLiquidity}
        </div>
      </div>
    </div>
  );
};

const AllPools = () => {
  const pools = usePools();
  if (!pools) return null;

  const [onlyFarms] = useFarmsOnly();
  const filteredPools = onlyFarms ? pools.filter((pool) => pool.incentiveKeys.some((key) => key.status === 'active')) : pools;
  console.log('pools', pools, filteredPools);

  return (
    <div className="mt-6 lt-mobile:mt-4">
      {filteredPools.map((p) => (
        <PoolItem key={p.poolAddress} data={p} />
      ))}
    </div>
  );
};

export default AllPools;
